server:
  port: 8082
  tomcat:
    threads:
      max: 200
      min-spare: 10

spring:
  application:
    name: tomcat-example
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
